### ISSUE TITLE
ImplicitStreamSubscription seems not working

### ISSUE THREAD

**Issue by dieron** [escendit/rabbitmq-orleans-extensions#39]
I replaced AddMemoryStreams with AddRabbitMqStreaming and it seems that  ImplicitStreamSubscription  isn't supported or I'm missing something.

**Comment by snovak7** [comment]
Hello, yes, normally I implement the IStreamSubscriptionObserver on the grain, and subscribe to the needed events.

**Comment by dieron** [comment]
I saw that attribute in the examples. So my initial thoughts were that it would be working. 

I like it because otherwise you have to find a way to make a grain to subscribe to a stream.

**Comment by snovak7** [comment]
ImplicitStreamSubscription does activate the grain when you use stream namespace in other parts of the solution, either you implement subscription in constructor or interface method... as a side note by default identity of grain equals the identity of stream, if that is not so you need to define StreamIdMapper (parameter of ImplicitStreamSubscriptionAttribute)

**Comment by dieron** [comment]
In my case, I see that all messages are moved from Ready to Unacked in RabbitMQ, but the activation of a grain doesn't happen. 

BTW, for the memory stream it only worked when I added this configuration option. 

`						.AddMemoryStreams("Transactions", configurator =>
						{
							configurator.ConfigureStreamPubSub(StreamPubSubType.ImplicitOnly);
						})
`
Without it, the activation didn't happen. 

Maybe I'm missing something important here.

**Comment by snovak7** [comment]
There is one more thing, you need GrainStorage with name PubSubStore, though I am not sure if needs to be explicitly set or works with Default

**Comment by dieron** [comment]
Changing it to .AddMemoryGrainStorage("PubSubStore") worked!

I'm not connecting dot's here, but you saved me another day :-)

I will continue testing the provider to see if I can use it with my next project. 

Thank you very much for your work!

**Comment by snovak7** [comment]
There is an intermediary grain in use which has some logic, I don't know the details... but there is some persistence in play.

I'm glad you got it working
